#ifndef LOGGERCATEGORIES_H
#define LOGGERCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logReportSaver)
Q_DECLARE_LOGGING_CATEGORY(logDbDataSender)
Q_DECLARE_LOGGING_CATEGORY(logModBusServer)
Q_DECLARE_LOGGING_CATEGORY(logTcpWriteReadClient)

#endif // LOGGERCATEGORIES_H
